spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llzw_dev?createDatabaseIfNotExist=true&autoReconnect=true
    username: llzw-dev
    password: HITllzw-dev!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
  data:
    rest:
      base-path: /api/v1
# If something weird happens in request mapping, you may need to uncomment this.
  resources:
    add-mappings: false

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8081