spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
        search:
          default:
            directory_provider: ram
            indexBase: /tmp
        enable_lazy_load_no_trans: true
  #        format_sql: true
  data:
    rest:
      base-path: /api/v1
  # If something weird happens in request mapping, you may need to uncomment this.
  resources:
    add-mappings: false
  profiles:
    include: etc

alipay:
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlKeI+QyAwSvgKY2j6i4vBo2lo8EvOHL/BrvWYWXIoDbzEKW3xhgEhkRRTdn7xdtNA/pIOS4Hmqo24GquFgZXGU2Jx9MxJDbqOG5maESB2P1G/TdaMK6KGKKvNQ6OVqG14o4lkCBmCFw8yfikF8oOD1fjxTpNAuC5KcdqBXe6ookeROFh/s+2BwQDW/hK6pERZSMjDnOVQxOhbmYMfSp2rCE+mDt4tGX+65d7Wvvbv/NC3z35v9lGHQoh8l+v9IJ+jkOf89RXBcDtz8btnb1My/H9g1LIm73Xb3eA/yqL4lrkvtal7TaUDar4Wl901Xltj70eQtyNSZyxF8igh2hwSQIDAQAB
  notify-url: http://hitnslab.com:8981/api/v1/payments/verify
  return-url: http://hitnslab.com:8981/api/v1/payments/verify
  app-id: 2016082000291463
  merchant-private-key: MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQC99RsiOnOJ2dbEc/13LODv7/Xlu5+colKTFhYjkBpcRSUe9JU3QYIDZTsYclJ4Rq4uaSsjYd5KbhvZK5U3jYs9lJllvxXFcvWF22wOAmA1ca//N7cBYiFhxeUHScUpMxYN0uhAjNayCASzc3OhhlieiGy2btw/WEfaFejWR42OUUn/UCTaEMN7pMLbHgk4GP7avpfaHs/KkIFU5zj/UjPZST5IzTpYw5JFPKUbx37Dz8d4c38susaS6nKWEQ9cQRRsLn8maDHjy5c93tAclA0iGJiJv0b9cYkumceizEK3YtJ+xJ9BUe97yTNOIhQ7XYIYu8OgZXGhat8tVYtSvHMUAfY7c1UM2eiBP3b9KuVPUbgJjpzUoGT508KfECh8ycXPlpSgsm50q9xJl3edCtlx++CBsu8p3IAywjDcAWj9xgKj23Hag/Aih13paoBkFnNcjJD2Gf+/BbB8KwpTlRXUCl1YhEcp1E2mPReuFo4lyXJ2s6uJPPBS5mXjXcCwV1uncoupS4KbYeSmG75ePk9K0ixCVGk0eWO7NL8aw2hn3YT4FCopH6HUnm7HWCMnMJ7a4dRrU/jgu7Cv69Sq79N5FbE+Itbu3bYIiBlCUv8EBEbLDWanMOMJYl4k9NO1O6MloF/hOjYIF1cXBXOAToaQoPjuVAXVtX4FVCId21EeHQIDAQABAoICAQCBShiDvYDyLICPCdtUiAk5hfu5t3A1rg3B6uB6qBQpBS702MfO6hlRsk78nqMfFgxrrk0cMfqYckUmFRHk08QXz9JwfBSXZV1TFDuBdYCCH7UIYqV+nYnXAFiYE0/McObr1ccaWEGwvuBkO4pSQByFGpnTubTSsIWHHC5z2hOw8AcLbUMH4S0MNOIjPVhNBEZCIEM+xIXte1lrrk0PCqYbmEx6RKUX0VT3JwXB2JChOgSsKQBAM4gAau4+0bHAutLppuQIAhci0mlIRSUkrmgZ8t+vsa7hxar3Ote0KI6oPuzCN5WlYd08RX9UCMH4ffaUWwgVXbZvhUwNkRHY6EbyBEamPMwysus/k4XmcdtjOjQUJ+uwrooVM7hTSVWqdlB0kyRskPIuQneiXAxnX2DkFRw79+aKW0aVLlK8niy7UzREAcuilYHgLcJTXn1L6AsQ7BQBVem6QqhwOnWw2inGYL5ZSuvyJ3EVZUbXYv0U8G5QhXVn8ySDRKi5qR09nG2BHhZLStsLmTAoxDnKfQ9ARhuZZUyIS+2uVIsI1ssIrPmKucUVW1L8UHplH3y63vu3bwePwQe5TxnAiIb89R1LN6X8rVZsqfzRDssKhoirQ6JxEbNIp7zbfDVBsyZIGFATsD5btDA8ZfWENrGOXlm7R8CKqIE7dc3owjymZNE9SQKCAQEA7Oa4RS2+svq6pzv6MMGI1vrPdjU+g99hlsjqBCovOgPl6MD3r/V2EmB4hLQkA54jaT8Icv5+GilnNo1C2sNWoKPE9r5cwg5cwQu6ZAXD9wQ6xV3Bu27ZxlqeZX+jKJ59Kl45K/QifE5sytunVuWqjUoRpo/smBTlkuG6Y4M3OmCfvBvKSlDAKviDpdw1pSAdnL3y1F+YXnpJzhntN7RsX0bhpeuk+NHqy7MWp9p26huGAEpJbG+yM+z0o06FP4TMAKXnlRSQ/DTXfKPgCK4d5aMM0WO4KECIdHvf9GCeD+ndochP5qb2x+6HfymuKDyJTCVlulnt09fcv6XeUK3a5wKCAQEAzUWJqD7WsPSUXH01ADZ0qiX/ou/UfpluPYSCG7OgYJ9Vy5KgPm5NJESiyIGXPYW8M6hdqqx3LZ8Al8WmHb5hRzAc2k3Kod3KmQB8f75A0owKSXkfQuWyLaek2IEb1pc5EBv9dx/6hqkZHB+CsSt7vio/reJuNhDvuWXAlWAWYQR01sZRTHqUftuvvo+IqqrNLHSjTzKojnDcuLfyzQbS/Hq3tFH3Jm5xIdZeNNX+3my0mwXXPw+LZXYeGSIJYfd2Vj7W2a6FUV/6mwRK2qYC8J0JJv4iPnKe54VI2DrUDcyE0OiDRhtOSwwURQYyPwkn0V3bH4JDRun97Qg70G2CWwKCAQEAo2YDxVtnBCYiJgUdbRGgI7+85qiU5PpnYkxT9Olvx5E2u9KVRJ2GgeheWBG0IXaqsAYU+tQEAGF8WkkWyrMfBg/PY+0rJ4ImgdRoDGNZpgAZ1VX0sSYlOUX5qMJftD2U0WtJ/cIXIywop8bXZf1lJKzo/byZkNAhBK2DFO5FYpOQuXtljNqjoT/l9bmsmqdLJXhyi/8fplKso2aIkvp0IUdPjlS5ZhHL5BIzVzU8/f5b78lNWWi1PlF670TSbVxYJT5JPC+CTSLZWpPhi7skzeYniilAtSrFs6pZb0JQ42MIRnVWfx28a2xfstr5z7Dpdkb5Io6yloJ2NQ3gCD/SEwKCAQBxeYB4row2dG5Tlq+m93OU376qzxPUDHNhtI/MSoddApgGGn9VI9qnMv4eA22dCAIbOHbXM9IKOTy1qgCDrsvN863vjFN5Gce2vwsT/xOMkPfa2AdNDvdpv6QkP3MpNJ3J5v8+TEJNEMudvVmdIWGdpXNgZ6zvXHt5LOPCb8TPSwxf8m/c7GKMoltL58LwPc2ARtZEoMeHPqL1xlKFvsEB68EEAM+0whbuUrfvU2E6ijNpA1iTNr+jjiFjWWqAarFTShexbIWsj3dVHJFYv68eXmFB2fkKNojbidXUGulA24+MgQyYw92LJRlLcvpx2FjXp5/LklIosI+76fJO7UrDAoIBAQCQLBohgRFloYSQY8e1lv/R8K8NODsk5AiPvKMqf8QtEOJqzkxeZgHMkhvK17pOlXi+RfIZ+T5OB0lxzl3viUVR8fF4kUW5HLtM6rdgLInuWBvG6FfgwYBsKKNgmrIW8/UFcbK8jGramy3sH6tm52d2zO8/+itORUbxgHipAcm0c0e5BD8W+oY3JUxiwGjUWL+BVkELIsrWm+ol94IPtii/cwkYbjcSXftRzrqT8blbq4ypy9sK53HrxaaaaJ/YQFOTSNtChOVaGiM86CBV2LEs6qjP1Q7rsCABFGsSXDioPvFWqo1Oq0uvhTgg0b3EucXia9PhFy3o7QQVNlkNSTb/
  gateway-url: https://openapi.alipaydev.com/gateway.do

llzw:
  test:
    load-users: true
    load-products: true
    load-stocks: true
    load-addresses-: true

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

server:
  port: 8981
  error:
    path: /api/v1/error